# Generated by Django 6.1.1 on 2026-10-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntreprisesApp', '0001_initial'),
        ('ExpeditionsApp', '0002_rename_datesouhaitee_expedition_date_souhaitee_and_more'),
        ('OffresApp', '0002_alter_offre_delai_jours_alter_offre_prix'),
        ('VehiculesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='offre',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'proposee')), fields=('expedition', 'entreprise'), name='unique_offre_proposee_par_entreprise_expedition'),
        ),
    ]
