# Generated by Django 6.1.1 on 2026-09-30 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntreprisesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(unique=True)),
                ('capacite_kg', models.PositiveIntegerField()),
                ('type_vehicule', models.CharField(choices=[('camion', 'Camion'), ('remorque', 'Remorque'), ('fourgon', 'Fourgon')], default='camion', max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EntreprisesApp.entreprise')),
            ],
        ),
    ]
