# Generated by Django 6.1.1 on 2026-09-30 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntreprisesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='EXP-BC1A6455', unique=True)),
                ('ville_depart', models.CharField()),
                ('ville_arrive', models.CharField()),
                ('poids_kg', models.DecimalField()),
                ('datesouhaitee', models.DateField()),
                ('desription', models.TextField()),
                ('statut', models.CharField(choices=[('publiee', 'Publiée'), ('attribuee', 'Attribuée'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='publiee', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to='EntreprisesApp.entreprise')),
            ],
        ),
    ]
