# Generated by Django 6.1.1 on 2026-09-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpeditionsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='reference',
            field=models.CharField(default='EXP-8B76F220', unique=True),
        ),
    ]
