# Generated by Django 6.1.1 on 2026-10-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpeditionsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expedition',
            old_name='datesouhaitee',
            new_name='date_souhaitee',
        ),
        migrations.RenameField(
            model_name='expedition',
            old_name='desription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='expedition',
            name='poids_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='reference',
            field=models.CharField(editable=False, max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='ville_arrive',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='ville_depart',
            field=models.CharField(max_length=100),
        ),
    ]
